version: '3.8'

services:
  # フロントエンド（Nginx）
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - mesh

  # バックエンド（Node.js API）
  backend:
    image: node:alpine
    ports:
      - "3001:3001"
    working_dir: /app
    command: sh -c "npm init -y && npm install express redis && node server.js"
    volumes:
      - ./server.js:/app/server.js
    depends_on:
      - redis
    networks:
      - mesh

  # データベース（Redis）
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mesh

networks:
  mesh:
    driver: bridge